### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by AdamsLab01** [Salamek/chromium-kiosk#56]
Hello, 

Base install of Debian 11 with GNOME. Went though the regular Debian install which has you create a user account. After install I SSHd to the system and as root following the instructions, installed chromium-kiosk and rebooted. After rebooting the system was at the login screen asking for the password of the user I setup during install. I set the system to login as  the chromium-kiosk user but only get the desktop, chromium-kiosk does not launch and the system times out to the login screen (also, don't know the password to the chromium-kiosk user).

Am I missing something to make this work?

**Comment by Salamek** [comment]
@AdamsLab01 You have to install this on barebone Debian (netinstall), in install setup just install SSH and base tools do not install any thing else...

**Comment by AdamsLab01** [comment]
> @AdamsLab01 You have to install this on barebone Debian (netinstall), in install setup just install SSH and base tools do not install any thing else...

Got it! Now installed and working... 

Couple questions:

Is there a way to enable the address bar so a user can type and address?

The IDLE_TIME option seems to cause a crash/not load. If I set a time, I tried just 5 and 300 (for 5 minutes) but when set I just get a blinking cursor in the upper left. I installed qiosk and need the "resets to default settings when idle" feature for my application to work.

Thanks, 

Adam

**Comment by Salamek** [comment]
> Is there a way to enable the address bar so a user can type and address?

You need address bar to be visible? I can implement configurable (on/off) address bar into `qiosk` if this is really important feature to you... 

> The IDLE_TIME option seems to cause a crash/not load. If I set a time, I tried just 5 and 300 (for 5 minutes) but when set I just get a blinking cursor in the upper left. I installed qiosk and need the "resets to default settings when idle" feature for my application to work.

`qiosk` backend is in beta, so some "hiccups" are expected...  ill test & fix it ASAP (give me a hour lol)

**Comment by Salamek** [comment]
@AdamsLab01 ok run.

```
apt update && apt upgrade
```

You should get update to `chromium-kiosk:1.0.4` fixing crash when using `IDLE_TIME`

**Comment by AdamsLab01** [comment]
Wow, you work fast! Really appreciate the response. 

I updated and with IDLE_TIME set it does not crash but it also does not seem to do anything. Navigating away from the home page the it just stays on the page you navigated to (FYI, I tried to enter the time as both seconds and minutes).

And, yes, I'm intending to use this as a public access terminal so having the address bar is needed. 

Thanks again.

**Comment by Salamek** [comment]
`IDLE_TIME` is in seconds, i just tested it and it works fine for me...

Are you sure that here is no input event? keyboard press, mouse move (Glitchy mouse moving cursor few PXs randomly)?

These events are considered as user activity:
```
QEvent::KeyPress
QEvent::MouseMove
QEvent::Wheel
QEvent::TouchUpdate
```

Ill ad that addressbar for you in meantime...

**Comment by Salamek** [comment]
@AdamsLab01 address bar like this is fine?
![Screenshot_2022-07-20_01-38-38](https://user-images.githubusercontent.com/1226241/179865947-ae09b6a4-e696-4317-bf75-0fe97f7abe63.jpg)

**Comment by AdamsLab01** [comment]
> @AdamsLab01 address bar like this is fine? ![Screenshot_2022-07-20_01-38-38](https://user-images.githubusercontent.com/1226241/179865947-ae09b6a4-e696-4317-bf75-0fe97f7abe63.jpg)

That's perfect

**Comment by AdamsLab01** [comment]
> `IDLE_TIME` is in seconds, i just tested it and it works fine for me...
> 
> Are you sure that here is no input event? keyboard press, mouse move (Glitchy mouse moving cursor few PXs randomly)?
> 
> These events are considered as user activity:
> 
> ```
> QEvent::KeyPress
> QEvent::MouseMove
> QEvent::Wheel
> QEvent::TouchUpdate
> ```
> 
> Ill ad that addressbar for you in meantime...

As a test, I unplugged the keyboard and mouse and still not seeing any change with IDLE_TIME set. I have it set to 60 seconds to test. Also, I tried enabling SCREEN_SAVER and it didn't trigger either.

**Comment by Salamek** [comment]
> > `IDLE_TIME` is in seconds, i just tested it and it works fine for me...
> > Are you sure that here is no input event? keyboard press, mouse move (Glitchy mouse moving cursor few PXs randomly)?
> > These events are considered as user activity:
> > ```
> > QEvent::KeyPress
> > QEvent::MouseMove
> > QEvent::Wheel
> > QEvent::TouchUpdate
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ill ad that addressbar for you in meantime...
> 
> As a test, I unplugged the keyboard and mouse and still not seeing any change with IDLE_TIME set. I have it set to 60 seconds to test. Also, I tried enabling SCREEN_SAVER and it didn't trigger either.

Can you post config.yml you are using? So i can upload it to my test rig in attempt to replicate your issue...

**Comment by AdamsLab01** [comment]
`FULL_SCREEN: true # Run in full screen mode, browser will use whole screen without any way for user to close it
TOUCHSCREEN: true # Enables support for touchscreen
HOME_PAGE: 'https://google.com'  # Url to load as homepage

# These works only with chromium-kiosk installed
IDLE_TIME: 60 # How log must be kiosk idle to redirect to HOME_PAGE, 0=disabled (Works only with chromium-kiosk extension installed)
WHITE_LIST:
  ENABLED: false  # is white list enabled
  URLS: []   # List of whitelisted urls, glob format is supported (eg,: *,google.*/news)
  IFRAME_ENABLED: true  # True to enable all iframes, list of urls to specify enabled iframes

NAV_BAR:
  ENABLED: true # is nav bar enabled
  ENABLED_BUTTONS: ['home', 'reload', 'back', 'forward'] # Enabled buttons on navbar, order matters
  HORIZONTAL_POSITION: 'center' # horizontal position on the screen
  VERTICAL_POSITION: 'bottom' # Vertical position on the screen
  WIDTH: 100 # Width of a bar in %
  HEIGHT: 5 # Height of a bar in % works only for qiosk

SCREEN_SAVER:
  ENABLED: false  # is screen saver enabled
  IDLE_TIME: 60
  TEXT: 'Touch me'

VIRTUAL_KEYBOARD:
  ENABLED: false

DISPLAY_ROTATION: 'normal' # normal|left|right|inverted
#SCREEN_ROTATION: 'normal'  #Rotates screen individually (do not rotate touchscreen) when X server starts options are (normal|left|right|inverted), remove DISPLAY_ROTATION for this to work
#TOUCHSCREEN_ROTATION: 'normal'  #Rotates touchscreen individually (do not rotate screen) when X server starts options are (normal|left|right|inverted), remove DISPLAY_ROTATION for this to work
#EXTRA_ARGUMENTS: # Pass extra arguments to used browser, in case of qiosk thse arguments are passed to chromium using QTWEBENGINE_CHROMIUM_FLAGS

# Allowed features in browser
# Uncomment feature you want to enable
#ALLOWED_FEATURES:
#  - desktop-audio-video-capture  # Allows recording desktop audio and video
#  - desktop-video-capture  # Allows recording desktop video
#  - geolocation  # Allows geolocation
#  - invalid-certificate  # Ignores invalid certificate
#  - media-audio-capture  # Allows recording audio from capture device (MIC)
#  - media-audio-video-capture  # Allows recording audio and video from capture device (Camera w/ MIC)
#  - media-video-capture  # Allows recording vide from capture device (Camera)
#  - mouse-lock  # Allows locking mouse inside browser full screen window
#  - notifications  # Allows notifications to be accepted from website
`

**Comment by AdamsLab01** [comment]
```
FULL_SCREEN: true # Run in full screen mode, browser will use whole screen without any way for user to close it
TOUCHSCREEN: true # Enables support for touchscreen
HOME_PAGE: 'https://google.com'  # Url to load as homepage

# These works only with chromium-kiosk installed
IDLE_TIME: 60 # How log must be kiosk idle to redirect to HOME_PAGE, 0=disabled (Works only with chromium-kiosk extension installed)
WHITE_LIST:
  ENABLED: false  # is white list enabled
  URLS: []   # List of whitelisted urls, glob format is supported (eg,: *,google.*/news)
  IFRAME_ENABLED: true  # True to enable all iframes, list of urls to specify enabled iframes

NAV_BAR:
  ENABLED: true # is nav bar enabled
  ENABLED_BUTTONS: ['home', 'reload', 'back', 'forward'] # Enabled buttons on navbar, order matters
  HORIZONTAL_POSITION: 'center' # horizontal position on the screen
  VERTICAL_POSITION: 'bottom' # Vertical position on the screen
  WIDTH: 100 # Width of a bar in %
  HEIGHT: 5 # Height of a bar in % works only for qiosk

SCREEN_SAVER:
  ENABLED: false  # is screen saver enabled
  IDLE_TIME: 60
  TEXT: 'Touch me'

VIRTUAL_KEYBOARD:
  ENABLED: false

DISPLAY_ROTATION: 'normal' # normal|left|right|inverted
#SCREEN_ROTATION: 'normal'  #Rotates screen individually (do not rotate touchscreen) when X server starts options are (normal|left|right|inverted), remove DISPLAY_ROTATION for this to work
#TOUCHSCREEN_ROTATION: 'normal'  #Rotates touchscreen individually (do not rotate screen) when X server starts options are (normal|left|right|inverted), remove DISPLAY_ROTATION for this to work
#EXTRA_ARGUMENTS: # Pass extra arguments to used browser, in case of qiosk thse arguments are passed to chromium using QTWEBENGINE_CHROMIUM_FLAGS

# Allowed features in browser
# Uncomment feature you want to enable
#ALLOWED_FEATURES:
#  - desktop-audio-video-capture  # Allows recording desktop audio and video
#  - desktop-video-capture  # Allows recording desktop video
#  - geolocation  # Allows geolocation
#  - invalid-certificate  # Ignores invalid certificate
#  - media-audio-capture  # Allows recording audio from capture device (MIC)
#  - media-audio-video-capture  # Allows recording audio and video from capture device (Camera w/ MIC)
#  - media-video-capture  # Allows recording vide from capture device (Camera)
#  - mouse-lock  # Allows locking mouse inside browser full screen window
#  - notifications  # Allows notifications to be accepted from website

```
